/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Univ3 } from "./Univ3";
export * as factories from "./factories";
export { Univ3__factory } from "./factories/Univ3__factory";
